const styles = {
    app: "min-h-[100vh] bg-gradient-to-r from-indigo-800 to-indigo-900",
    main: "flex justify-center p-4 md:p-12 lg:p-14",
    container: "max-w-[800px] w-full flex flex-col gap-4",
    habitsContainer: "flex flex-col gap-4",
    confettiCanvas: "w-full h-full pointer-events-none fixed top-0 left-0",
    heading: "text-3xl font-bold text-center text-slate-50 animate-fade-down animate-duration-1000 animate-delay-500",
    habitInput: "flex flex-col gap-4",
    label: "block mb-2 text-sm font-medium text-gray-900 dark:text-white animate-fade-down animate-duration-1000 animate-delay-500",
    inputcontainer: "flex justify-between gap-4 animate-fade-down animate-duration-1000 animate-delay-500",
    input: "inline bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5",
    invalidInput: "inline bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 border-red-500 border-2",
    button: "p-4 ml-2 bg-sky-500 text-slate-100 rounded-lg hover:bg-sky-300 focus:ring-4 focus:outline-none focus:ring-sky-800",
    habit: "relative w-full bg-neutral-50 rounded-lg text-gray-500 flex flex-col animate-fade-down animate-duration-1000 animate-delay-500",
    habitInfo: "flex justify-between p-4",
    options: "text-3xl flex items-center gap-2",
    habitGraph: "text-sm sm:text-md grid grid-rows-7 grid-cols-3 sm:grid-rows-6 sm:grid-cols-4 md:grid-rows-5 md:grid-cols-5 lg:grid-rows-4 lg:grid-cols-6 grid-flow-col gap-2 p-4",
    graphSection: "w-full self-start",
    list: "flex gap-2 hover:text-black cursor-pointer",
    dropdown: "text-3xl focus:scale-110",
    deleteicon: "text-xl text-white bg-red-500 border-2 border-red-500 rounded-md cursor-pointer focus:outline-2 focus:outline-red-700 focus:outline-double",
    popupcontainer: "relative",
    updateicon: "text-xl text-sky-500 rounded-md cursor-pointer focus:scale-110",
    updatepopup: "absolute flex flex-col shadow-md gap-2 bottom-8 right-1 p-2 bg-white rounded-md text-sm text-gray-700 z-10 border-8 border-solid border-white border-t-transparent border-r-transparent border-l-transparent border-b-white animate-fade-up animate-duration-1000",
    updateinput: "border-2 border-slate-500 p-2 focus:border-black rounded-md",
    updateinputInvalid: "border-2 border-red-500 p-2 focus:border-black rounded-md",
    updatebtn: "text-center text-white bg-sky-500 rounded-lg p-1 hover:scale-95 focus:outline-2 focus:outline-sky-700 focus:outline-double ease-in transition duration-150 ease-in hover:ease-in",
    deletetext: "text-sm",
    deletepopup: "absolute w-72 flex flex-col shadow-md gap-2 bottom-8 right-1 p-2 bg-white rounded-md text-sm text-gray-700 z-10 border-8 border-solid border-white border-t-transparent border-r-transparent border-l-transparent border-b-white animate-fade-up animate-duration-1000",
    deletebtn: "text-center text-white bg-red-500 rounded-lg p-1 hover:scale-95 focus:outline-2 focus:outline-red-700 focus:outline-double ease-in transition duration-150 ease-in hover:ease-in",
    congratstext: "text-lg md:text-2xl text-center text-black p-2 pb-6 animate-fade-down animate-duration-1000"
};

export default styles;